version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Benjamin_prod
    ports:
      - '8080:80'
    environment:
      - REACT_APP_NAME=BENJAMIN-prod
    env_file:
      - ./.env
